<div id="new-product" class="row col-md-8" style="border-right: solid; overflow: scroll; height: 600px">

    <div class="row" id="top-head">
        <div class="col-md-12">
            <div class="pull-left">
                <button type="button" class="btn btn-back btn-primary"><i class="fa fa-backward"></i>Back</button>
            </div>
        </div>
    </div>

    <form class="form-horizontal" role="form" method="POST" action="{{ url('product/productIndex') }}" accept-charset="UTF-8" enctype="multipart/form-data">
        {{ csrf_field() }}

        <table class="table table-striped table-striped table-responsive table-success">
            <tbody>
            <tr>
                <td><label for="name" class="control-label">Name <span style="color: red">*</span></label></td>
                <td colspan="3"><input id="name" type="text" class="form-control" name="name" value=""  autocomplete="off"></td>
            </tr>
            <tr>
                <td><label for="category_id" class="control-label">Category<span style="color: red">*</span></label></td>
                <td>{!! Form::select('category_id', $categories , null , array('id' => 'category_id', 'class' => 'form-control')) !!}</td>
                <td><label for="subcategory_id" class="control-label">Sub Category<span style="color: red">*</span></label></td>
                <td>{!! Form::select('subcategory_id', $subcategories , null , array('id' => 'subcategory_id', 'class' => 'form-control')) !!}</td>
            </tr>

            <tr>
                <td><label for="brand_id" class="control-label">Brand<span style="color: red">*</span></label></td>
                <td>{!! Form::select('brand_id', $brands , 1 , array('id' => 'brand_id', 'class' => 'form-control')) !!}</td>
                <td><label for="unit_name" class="control-label">Unit<span style="color: red">*</span></label></td>
                <td>{!! Form::select('unit_name', $units , null , array('id' => 'unit_name', 'class' => 'form-control')) !!}</td>
            </tr>

            <tr>
                <td><label for="second_unit" class="control-label">Second Unit</label></td>
                <td>{!! Form::select('second_unit', $units , null , array('id' => 'second_unit', 'class' => 'form-control','placeholder' => 'Second Unit...')) !!}</td>
                <td><label for="third_unit" class="control-label">Third Unit</label></td>
                <td>{!! Form::select('third_unit', $units , null , array('id' => 'third_unit', 'class' => 'form-control','placeholder' => 'Third Unit...')) !!}</td>
            </tr>

            <tr>
                <td><label for="size_id" class="control-label">Size<span style="color: red">*</span></label></td>
                <td>{!! Form::select('size_id', $sizes , 1 , array('id' => 'size_id', 'class' => 'form-control')) !!}</td>
                <td><label for="color_id" class="control-label">Color<span style="color: red">*</span></label></td>
                <td>{!! Form::select('color_id', $colors , null , array('id' => 'color_id', 'class' => 'form-control')) !!}</td>
            </tr>

            <tr>
                <td><label for="godown_id" class="control-label">Store<span style="color: red">*</span></label></td>
                <td>{!! Form::select('godown_id', $stores , null , array('id' => 'godown_id', 'class' => 'form-control')) !!}</td>
                <td><label for="rack_id" class="control-label">Rack<span style="color: red">*</span></label></td>
                <td>{!! Form::select('rack_id', $racks , null , array('id' => 'rack_id', 'class' => 'form-control')) !!}</td>
            </tr>

            <tr>
                <td><label for="sku" class="control-label">SKU<span style="color: red">*</span></label></td>
                <td><input id="sku" type="text" class="form-control" name="sku" value="" required autocomplete="off"></td>
                <td><label for="autosku" class="control-label" style="text-align: left">SKU Autogenerated</label></td>
                <td><input type="checkbox" name="auto_sku" id="auto_sku" data-toggle="toggle" data-onstyle="primary"></td>
            </tr>

            <tr>
                <td><label for="model_id" class="control-label">Model<span style="color: red">*</span></label></td>
                <td>{!! Form::select('model_id', $models , null , array('id' => 'model_id', 'class' => 'form-control')) !!}</td>
                <td><label for="tax_id" class="control-label">Tax<span style="color: red">*</span></label></td>
                <td>{!! Form::select('tax_id', $taxes , null , array('id' => 'tax_id', 'class' => 'form-control')) !!}</td>
            </tr>

            <tr>
                <td><label for="reorder_point" class="control-label">Reorder Level</label></td>
                <td><input id="reorder_point" type="text" class="form-control" name="reorder_point" value="{!! 0 !!}" required></td>
                <td><label for="expiry_date" class="control-label" style="text-align: left">Expiry Date</label></td>
                <td><input id="expiry_date" type="text" class="form-control" name="expiry_date" value="{!! \Carbon\Carbon::now()->format('d-m-Y') !!}" readonly></td>
            </tr>

            <tr>
                <td><label for="description_short" class="control-label">Short Description</label></td>
                <td>{!! Form::textarea('description_short',null,['id'=>'description_short','size' => '20x3','class'=>'field']) !!}</td>
                <td><label for="description_long" class="control-label">Long Description</label></td>
                <td>{!! Form::textarea('description_long',null,['id'=>'description_long','size' => '20x3','class'=>'field']) !!}</td>
            </tr>

            <tr>
                <td colspan="3">Upload Product Image</td>
                <td>
                    <div class="imageupload">
                        <div class="file-tab">
                            <label class="btn btn-success btn-file">
                                <span>Upload</span>
                                <!-- The file is stored here. -->
                                <input type="file" name="product-image" id="product-image">
                            </label>
                            <button type="button" class="btn btn-default">Remove</button>
                        </div>
                    </div>

                </td>
            </tr>


            </tbody>
        </table>


        <div class="col-md-10 col-md-offset-1">
            <button type="submit" class="btn btn-primary pull-right">Submit</button>
            <button type="button" class="btn btn-danger pull-left" data-dismiss="modal">Cancel</button>
        </div>

    </form>

</div>

<div style="width: 5px"></div>

{{--<div class="col-md-2 col-md-offset-1">--}}
{{--    <article>--}}
{{--        <h1>Help Tips</h1>--}}
{{--        <p>Insert All the related data to the related input fields</p>--}}
{{--    </article>--}}

{{--    <p><strong>Note:</strong> Please upload image size width = 400px and Height=520px</p>--}}
{{--</div>--}}

